receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  kafka:
    brokers:
      - kafka:29092
    encoding: otlp_json

  prometheus:
    endpoint: otel-collector:8889

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    tls:
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin,jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
#  telemetry:
#    logs:
#      level: debug