version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'metric-app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dev-infra

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.47
    ports:
      - 16686:16686
      - 14250:14250
    networks:
      - dev-infra

  app:
    container_name: app
    build: 
      context: ../
      dockerfile: DockerFile
    environment:
      - OTEL_SERVICE_NAME=my-application
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
    ports:
      - 8080:8080
    networks:
      - dev-infra
    depends_on:
      - jaeger
      - db

networks:
  dev-infra:
    external: true
    name: dev-infra
volumes:
  my-db: